// +build ignore

package main

import (
	"io/ioutil"
	"os"
	"path/filepath"
)

func main() {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	out, err := os.Create(filepath.Join(wd, "launcher", "template.go"))
	if err != nil {
		panic(err)
	}

	template := filepath.Join(wd, "launcher", "bastion-role-cf.tmpl")
	ingressTemplate := filepath.Join(wd, "etc", "bastion-ingress-cf.template")
	roleTemplate := filepath.Join(wd, "launcher", "role-cf.tmpl")

	out.Write([]byte("// This file is autogenerated; DO NOT EDIT\n// See generate.go for more info.\npackage launcher\n\n"))

	out.Write([]byte("const BastionAndRoleTemplate = `"))

	t, err := ioutil.ReadFile(template)
	if err != nil {
		panic(err)
	}

	out.Write([]byte(t))
	out.Write([]byte("`\n\nconst BastionIngressTemplate = `"))

	t, err = ioutil.ReadFile(ingressTemplate)
	if err != nil {
		panic(err)
	}

	out.Write([]byte(t))
	out.Write([]byte("`\n\nconst RoleTemplate = `"))
	t, err = ioutil.ReadFile(roleTemplate)
	if err != nil {
		panic(err)
	}

	out.Write([]byte(t))
	out.Write([]byte("`\n"))
}
